name: CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Go Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup go
        uses: actions/setup-go@v3

      - name: Lint with golangci-lint
        uses: golangci/golangci-lint-action@v3

  coverage:
    name: Go Coverage
    needs:
      - lint
    strategy:
      matrix:
        version:
          - 1.12
          - 1.13
          - 1.14
          - 1.15
          - 1.16
          - 1.17
          - 1.18
          - 1.19
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go ${{ matrix.version }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.version }}

    - name: Build
      run: go build -v ./...

    - name: Unit test
      run: go test -v ./...

    - name: Coverage test
      run: go test -covermode=count -coverprofile=coverage.txt ./...

    - uses: codecov/codecov-action@v3
      with:
        files: ./coverage.txt
        fail_ci_if_error: true
        verbose: true
